### ISSUE TITLE
Add ChatParameters for chat specific config

### ISSUE THREAD

**Issue by stargazing-dino** [jeremychone/rust-genai#3]
I need the ability to set temperature and max tokens but currently nothing is provided.

In my head here's something of what the API might look like

```rs
use genai::chat::{ChatMessage, ChatRequest, ChatParameters};
use genai::client::Client;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::default();
    let parameters = ChatParameters::new()
        .with_max_tokens(2000)
        .with_temperature(0.7)
        .with_top_p(0.9);

    let chat_req = ChatRequest::new(vec![
        ChatMessage::user("Tell me a short story about a robot."),
    ]).with_parameters(parameters);

    let chat_res = client.exec_chat("gpt-3.5-turbo", chat_req, None).await?;
    println!("{}", chat_res.content.unwrap_or_default());

    Ok(())
}
```

Thoughts?

**Comment by jeremychone** [comment]
Yes, this is coming. There was a [PR 1](#1) for this, but it was not done the way I was planning to do it (for now).

So, the plan was to use the `ChatRequestOptions` for that, and pass those flat in the `ChatRequestOptions`.

So, something like this:

```rust
pub struct ChatRequestOptions {
    // vvv Will be implemented in 0.1.2 vvv
    pub temperature: Option<i32>,
    pub max_token: Option<u32>, // might be i32 for simplicity (not sure yet)
    // ^^^
    
    
    /// Will capture the `MetaUsage`
    /// - In the `ChatResponse` for `exec_chat`
    /// - In the `StreamEnd` of `StreamEvent::End(StreamEnd)` for `exec_chat_stream`
    pub capture_usage: Option<bool>,

    // -- For Stream only (for now, we flat them out)
    /// Tell the chat stream executor to capture and concatenate all of the text chunks
    /// to the last `StreamEvent::End(StreamEnd)` event as `StreamEnd.captured_content` (so, will be `Some(concatenated_chunks)`)
    pub capture_content: Option<bool>,
}
```

The `ChatRequestOptions` struct was about passin those kind of eventual values to either genai internal or to the AI provider/adapter. 


What do you think? 

I will add a feature ticket about this one and link this ticket.

**Comment by stargazing-dino** [comment]
that's great this is already in the pipeline and yeah your method seems very good.

In any case, once you have code feel free to ping me for a review if you'd like

**Comment by jeremychone** [comment]
@stargazing-dino hey, you can check the latest `main` branch and the `examples/c04-req-options.rs`. I added temperature, max_tokens, top_p, and support for all adapters.

I have also added cascading option support, meaning you can set default values for those properties at the "client config" level and then override them at the chat exec level.

**Comment by jeremychone** [comment]
@stargazing-dino Implemented in `v0.1.2`

**Comment by stargazing-dino** [comment]
Very cool ! 🔥

I quickly looked at the code and my only notes are on `ChatRequestOptionsSet` and `x_deep_set`:

- I'm not sure exactly why it's used but my naive thought was it could be replaced with a merge options fn:

```rs
// avoids lifetimes no?
fn merge_options(client_options: &ChatRequestOptions, request_options: &ChatRequestOptions) -> ChatRequestOptions {
    ChatRequestOptions {
        temperature: request_options.temperature.or(client_options.temperature),
        max_tokens: request_options.max_tokens.or(client_options.max_tokens),
        top_p: request_options.top_p.or(client_options.top_p),
        // ... other fields
    }
}
```

or something even less formal.

the `x_value.rs` I'm less sure on but it feels like it could be replaced with something like [serde_path_to_error](https://docs.rs/serde_path_to_error/latest/serde_path_to_error/) or similar? I thought it was lenses at first but it's just modifying the json structure i think

In any case, very happy to see the changes nonetheless :)

**Comment by jeremychone** [comment]
Ok, on those two points:

- ChatRequestOptionsSet: Having a `merge_options` could be a valid alternative. The current design is because eventually, we might have another layer, like per adapter or even per model ChatRequestOptions, and the on-demand approach works well. But even with this requirement, the `merge_options` might be acceptable at some point. The main reason I am avoiding it for now is that I do not know if, at some point, I would need large strings in the ChatRequestOptions. So, having a code design that avoids the clone is good. Right now, there are just copy types, so either way would work relatively the same.

- `x_deep_insert`: This helper method will eventually replace the `x_insert` as we do not need to have both functions. I just wanted to release `0.1.2` today, so I took this implementation detail shortcut. I am not sure `serde_path_to_error` will help much or be much better than the current implementation. But it might be, and this could be changed if needed. The nice thing about the XValue design is that these are just internal implementation details.

**Comment by stargazing-dino** [comment]
Yeah for sure, that all sounds good.

I'll test out the actual lib/api once I'm working on my hobby project sometime this week and let you know how it goes
